name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Get directory
      run: ls
    - name: Build the Docker image
      run: docker build -t thanoojdocker/springdatarest .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: thanoojdocker
        password: sai123sai
    - name: Push the Docker image
      run: docker push thanoojdocker/springdatarest
